ppw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story1_app.urls')),
    path('', include('story4_app.urls')),
    path('', include('story5_app.urls')),
    path('', include('story6_app.urls')),
    path('', include('story7_app.urls')),
    path('', include('story8_app.urls')),
    path('', include('story9_app.urls')),
]

story1_app/urls.py
from django.urls import path
from . import views

app_name = 'story1_app'
urlpatterns = [
    path('', views.home_view, name="home_url"),
]

story5_app/urls.py
from django.urls import path
from . import views

app_name = 'story5_app'
urlpatterns = [
    path('add', views.form_matkul, name="form_url"),
    path('detail/<int:id>', views.detail_matkul, name="detail_url"),
    path('list-matkul', views.mata_kuliah, name="listmatkul_url"),
]

story5_app/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
SEMESTER_CHOICES = ( 
    ("Gasal 2020/2021", "Gasal 2020/2021"),
    ("Genap 2019/2020", "Genap 2019/2020"), 
    ("Gasal 2019/2020", "Gasal 2019/2020"),
    ("Other", "Other"),
)

class MataKuliah(models.Model):
    nama_matkul = models.CharField(
        'Mata Kuliah', 
        max_length = 100, 
        help_text = 'PPW'
    )
    dosen_pengajar = models.CharField(
        'Dosen Pengajar', 
        max_length = 100, 
        help_text = 'Gladhi Guarddin S.Kom., M. Kom.'
    )
    jumlah_sks = models.IntegerField(
        'Jumlah SKS',
        default = 1,
        validators = [
            MinValueValidator(1),
            MaxValueValidator(24)
        ]
    )
    deskripsi = models.CharField(
        'Deskripsi',
        max_length = 500
    )
    semester_tahun = models.CharField(
        'Semester Tahun',
        max_length = 15,
        choices = SEMESTER_CHOICES,
        default = 'Gasal 2020/2021'
    )
    ruang_kelas = models.CharField(
        'Ruang Kelas', 
        max_length = 20,
        help_text = 'A1.07')

    def __str__(self):
        return f'{self.nama_matkul}'

story5_app/forms.py
from django.forms import ModelForm
from .models import MataKuliah

class MataKuliahForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, value in self.fields.items():
            value.widget.attrs['placeholder'] = value.help_text

    class Meta:
        model = MataKuliah
        fields = '__all__'

story5_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import MataKuliah
from .forms import MataKuliahForm

# Create your views here.
def mata_kuliah(request):
    if (request.method == 'POST'):
        MataKuliah.objects.get(id = request.POST['id']).delete()

    mataKuliah = MataKuliah.objects.all()
    html = 'pages/mata-kuliah.html'
    return render(request, html, {'mata_kuliah': mataKuliah})

def detail_matkul(request, id):
    if (request.method == 'POST'):
        MataKuliah.objects.get(id = request.POST['id']).delete()
        mataKuliah = MataKuliah.objects.all()
        html = 'pages/mata-kuliah.html'
        return render(request, html, {'mata_kuliah': mataKuliah})

    mataKuliah = MataKuliah.objects.get(pk = id)
    html = 'pages/detail-matkul.html'
    return render(request, html, {'mata_kuliah': mataKuliah})

def form_matkul(request):
    form = MataKuliahForm(request.POST or None)
    html = 'pages/form-matkul.html'
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/list-matkul')
    else:
        return render(request, html, {'form': form})

story5_app/templates/pages/detail-matkul.html
{% extends 'app-shell.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/matkul.css' %}"/>
<title>Cornelita | Detail Kuliah</title>
{% endblock meta %}

{% block content %}
<main class="container">
    <h1 class="sub-title">Detail Mata Kuliah</h1>
    <h3 class="sub-title">{{ mata_kuliah.nama_matkul }}</h3>
    <div class="row mx-2">
        <div class="col col-12 col-md-4 text-bold">Dosen Pengajar :</div>
        <div class="col col-12 col-md-8">{{ mata_kuliah.dosen_pengajar }}</div>
        
        <div class="col col-12 col-md-4 text-bold">Jumlah SKS :</div>
        <div class="col col-12 col-md-8">{{ mata_kuliah.jumlah_sks }}</div>

        <div class="col col-12 col-md-4 text-bold">Deskripsi :</div>
        <div class="col col-12 col-md-8">{{ mata_kuliah.deskripsi }}</div>
        
        <div class="col col-12 col-md-4 text-bold">Semester Tahun :</div>
        <div class="col col-12 col-md-8">{{ mata_kuliah.semester_tahun }}</div>

        <div class="col col-12 col-md-4 text-bold">Ruang Kelas :</div>
        <div class="col col-12 col-md-8">{{ mata_kuliah.ruang_kelas }}</div>

        <div class="col col-12 center-content">
            <button class="btn myButton">
                <a href="{% url 'story5_app:listmatkul_url' %}" class="myButton"><i class="fas fa-arrow-left"></i> Return</a>
            </button>
            <form method="POST" action="" style="display: inline-block;">
                {% csrf_token %}
                <input name="id" value="{{ mata_kuliah.id }}" type="hidden">
                <button type="submit" class="btn myButton"><i class="far fa-times-circle"></i> Delete</button>
            </form>
        </div>
    </div>
</main>
{% endblock content %}

story5_app/templates/pages/form-matkul.html
{% extends 'app-shell.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/matkul.css' %}"/>
<title>Cornelita | Add Mata Kuliah</title>
{% endblock meta %}

{% block content %}
<main class="container">
    <h1 class="sub-title">Tambah Mata Kuliah</h1>
    <form action="" method="POST" novalidate>
        {% csrf_token %}
        <table class="table">
            {{ form.as_table }}
            <tr>
                <td class="center-content" colspan="2">
                    <input type="submit" value="Submit" class="btn myButton">
                </td>
            </tr>
        </table>
    </form>
</main>
{% endblock content %}

story5_app/templates/pages/mata-kuliah.html
{% extends 'app-shell.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/matkul.css' %}"/>
<title>Cornelita | Kuliah</title>
{% endblock meta %}

{% block content %}
<main class="container">
    <h1 class="sub-title">List Mata Kuliah</h1>
    <div class="row justify-content-center mb-44">
        {% for matkul in mata_kuliah %}
            <div class="col-11 col-md-5 col-lg-3 d-flex justify-content-between align-items-center brown-border m-1">
                <a href="{% url 'story5_app:detail_url' matkul.id %}" class="nama_matkul"><h2>{{ matkul.nama_matkul }}</h2></a>
                <form method="POST" action="">
                    {% csrf_token %}
                    <input name="id" value="{{ matkul.id }}" type="hidden">
                    <button type="submit" class="btn delete"><i class="far fa-times-circle"></i></button>
                </form>
            </div>
        {% empty %}
            <h4>Hmm.... belum ada mata kuliah yang terdata.</h4>
        {% endfor %}
    </div>
    <div class="row justify-content-center">
        <a href="/add"><button class="btn myButton">Tambah Mata Kuliah</button></a>
    </div>
    
</main>
{% endblock content %}