ppw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story1_app.urls')),
    path('', include('story4_app.urls')),
    path('', include('story5_app.urls')),
    path('', include('story6_app.urls')),
    path('', include('story7_app.urls')),
    path('', include('story8_app.urls')),
    path('', include('story9_app.urls')),
]

story1_app/urls.py
from django.urls import path
from . import views

app_name = 'story1_app'
urlpatterns = [
    path('', views.home_view, name="home_url"),
]

story6_app/urls.py
from django.urls import path
from . import views

app_name = 'story6_app'
urlpatterns = [
    path('addPerson/<int:idActivity>', views.addPerson, name="add_person_url"),
    path('addActivity', views.addActivity, name="add_activity_url"),
    path('activity', views.my_activity, name="activity_url"),
]

story6_app/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    person_name = models.CharField(
        'Nama',
        max_length = 100, 
        help_text = 'Cornelita',
        unique = True
    )

class Activity(models.Model):
    activity_name = models.CharField(
        'Judul Kegiatan', 
        max_length = 100, 
        help_text = 'Menangis T-T'
    )
    list_person = models.ManyToManyField(Person)

story6_app/forms.py
from django.forms import ModelForm
from .models import Activity, Person

class PersonForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, value in self.fields.items():
            value.widget.attrs['placeholder'] = value.help_text

    class Meta:
        model = Person
        fields = '__all__'

class ActivityForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, value in self.fields.items():
            value.widget.attrs['placeholder'] = value.help_text

    class Meta:
        model = Activity
        fields = [
            'activity_name'
        ]

story6_app/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError
from .models import Activity, Person
from .forms import ActivityForm, PersonForm

# Create your views here.
def my_activity(request):
    formPerson = PersonForm()
    formActivity = ActivityForm()
    activities = Activity.objects.all()
    html = "pages/activity.html"
    return render(request, html, {'formPerson': formPerson, 'formActivity': formActivity, 'activities': activities})

def getPerson(name):
    person = Person.objects.filter(person_name = name)
    if person.exists():
        return person.first()
    else:
        return False

def addPerson(request, idActivity):
    formPerson = PersonForm(request.POST)
    activity = Activity.objects.filter(pk = idActivity)
    if (activity.exists()) :
        if formPerson.is_valid():
            person = formPerson.save()
            activity.first().list_person.add(person)
        else :
            person = getPerson(request.POST['person_name'])
            if person:
                activity.first().list_person.add(person)
    return redirect('story6_app:activity_url')

def addActivity(request):
    formActivity = ActivityForm(request.POST)
    if (formActivity.is_valid()):
        formActivity.save()
    return redirect('story6_app:activity_url')

story6_app/templates/pages/activity.html
{% extends 'app-shell.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/activity.css' %}"/>
<title>Cornelita | Activity</title>
{% endblock meta %}

{% block content %}
<main class="container">
    <h1 class="sub-title">Daftar Kegiatan Lita</h1>
    <div class="row my-5">
        <div class="card text-center w-100">
            <div class="card-body">
                <h3 class="card-title">Tambah Kegiatan</h3>
                <form method="POST" action="{% url 'story6_app:add_activity_url' %}">
                    {% csrf_token %}
                    {{ formActivity.as_p }}
                    <input type="submit" value="Tambah Kegiatan" class="btn myButton">
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="card-deck">
        {% for activity in activities %}
            <div class="card text-center">
                <h2 class="card-header">{{ activity.activity_name }}</h2>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                    {% for person in activity.list_person.all %}
                        <li class="list-group-item">{{ person.person_name }}</li>
                    {% empty %}
                        <li class="list-group-item">Belum ada peserta</li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="card-footer">
                    <form method="POST" action="{% url 'story6_app:add_person_url' activity.id %}">
                        {% csrf_token %}
                        {{ formPerson.as_p }}
                        <input type="submit" value="Daftar" class="btn btn-primary">
                    </form>
                </div>
            </div>
        {% empty %}
            <h4>Belum ada kegiatan</h4>
        {% endfor %}
        </div>
    </div>
</main>
{% endblock content %}