ppw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story1_app.urls')),
    path('', include('story4_app.urls')),
    path('', include('story5_app.urls')),
    path('', include('story6_app.urls')),
    path('', include('story7_app.urls')),
    path('', include('story8_app.urls')),
    path('', include('story9_app.urls')),
]

story1_app/urls.py
from django.urls import path
from . import views

app_name = 'story1_app'
urlpatterns = [
    path('', views.home_view, name="home_url"),
]

story9_app/urls.py
from django.urls import path, include
from . import views

app_name = 'story9_app'
urlpatterns = [
    path('surprise', views.showSurprise, name="surprise"),
    path('login', views.loginPage, name='login'),
    path('register', views.registerPage, name='register'),
    path('logout', views.logoutUser, name='logout'),
]

story9_app/models.py
from django.db import models

# Create your models here.

story9_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

story9_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def showSurprise(request):
    html = 'pages/surprisePage.html'
    return render(request, html)

def logoutUser(request):
    logout(request)
    return redirect('story9_app:surprise')

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('story9_app:surprise')
    else:
        html = 'pages/login.html'
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username = username, password = password)

            if user is not None:
                login(request, user)
                return redirect('story9_app:surprise')
            else:
                messages.info(request, 'Username or password is incorrect')
                return render(request, html)
        return render(request, html)

def registerPage(request):
    if request.user.is_authenticated:
        return redirect('story9_app:surprise')
    else:
        form = RegisterForm()

        if request.method == 'POST':
            form = RegisterForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)
                return redirect('story9_app:login')

        context = {'form' : form}
        html = 'pages/register.html'
        return render(request, html, context)

story9_app/templates/pages/login.html
{% extends 'app-shell.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/story9.css' %}"/>
<title>Cornelita | Story 9</title>
{% endblock meta %}

{% block content %}
<main class="container">
    <h1 class="sub-title">Story 9 | Login</h1>
    
    <form method="POST" action="{% url 'story9_app:login' %}">
        {% csrf_token %}
        <table class="table">
            <tr>
                <td><label for="username">Username</label></td>
                <td><input type="text" name="username" id="username" placeholder="Username..."></td>
            </tr>
            <tr>
                <td><label for="password">Password</label></td>
                <td><input type="password" name="password" id="password" placeholder="Password..."></td>
            </tr>
            <tr>
                <td colspan="2">
                    <input class="btn myButton" type="submit" value="Login" name="Login">
                </td>
            </tr>
            <tr>
                {% for message in messages %}
                    <td colspan="2"><p class="messages">{{ message }}</p></td>
                {% endfor %}
            </tr>
            <tfoot>
                <tr>
                    <td colspan="2">Didn't have an account? <a href="{% url 'story9_app:register' %}">Register Now</a></td>
                </tr>
            </tfoot>
        </table>
    </form>
        
</main>
{% endblock content %}

story9_app/templates/pages/register.html
{% extends 'app-shell.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/story9.css' %}"/>
<title>Cornelita | Story 9</title>
{% endblock meta %}

{% block content %}
<main class="container">
    <h1 class="sub-title">Story 9 | Register</h1>
    <p class="center">Already have an account? <a href="{% url 'story9_app:login' %}">Login</a></p>
    <div class="center-item">
        {% if form.errors %}
            <div class="error-message">
                {{ form.errors }}
            </div>
        {% endif %}
    </div>
    <form method="POST" action="">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ form|crispy }}
        </fieldset>
        <input class="btn myButton" type="submit" value="Sign Up" name="Register User">
    </form>
</main>
{% endblock content %}

story9_app/templates/pages/surprisePage.html
{% extends 'app-shell.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/story9.css' %}"/>
<title>Cornelita | Story 9</title>
{% endblock meta %}

{% block content %}
<main class="container">
    {% if user.is_authenticated %}
    <h1 class="congrats">Hello {{ user.get_username }}!</h1>
    {% endif %}
    <h1 class="congrats">🎊 It's Last Story 🎊</h1>
    <div class="center">
        {% if user.is_authenticated %}
            <img id="surpriseImage" src="{% static 'images/kucing.jpg' %}">
            <a class="btn myButton" href="{% url 'story9_app:logout' %}">Logout</a>
        {% else %}
            <h4>Want to see something exciting?</h4>
            <a class="btn myButton" href="{% url 'story9_app:login' %}">Login</a>
        {% endif %}
    </div>
</main>
{% endblock content %}