ppw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story1_app.urls')),
    path('', include('story4_app.urls')),
    path('', include('story5_app.urls')),
    path('', include('story6_app.urls')),
    path('', include('story7_app.urls')),
    path('', include('story8_app.urls')),
    path('', include('story9_app.urls')),
]

story1_app/urls.py
from django.urls import path
from . import views

app_name = 'story1_app'
urlpatterns = [
    path('', views.home_view, name="home_url"),
]

story4_app/urls.py
from django.urls import path
from . import views

app_name = 'story4_app'
urlpatterns = [
    path('riwayat', views.riwayat_view, name="riwayat_url"),
    path('portofolio', views.portofolio_view, name="portofolio_url"),
    path('logs', views.logs_view, name="logs_url"),
]

story6_app/urls.py
from django.urls import path
from . import views

app_name = 'story6_app'
urlpatterns = [
    path('addPerson/<int:idActivity>', views.addPerson, name="add_person_url"),
    path('addActivity', views.addActivity, name="add_activity_url"),
    path('activity', views.my_activity, name="activity_url"),
]

story7_app/urls.py
from django.urls import path
from . import views

app_name = 'story7_app'
urlpatterns = [
    path('story7', views.showPage, name="story7"),
]

story8_app/urls.py
from django.urls import path
from . import views

app_name = 'story8_app'
urlpatterns = [
    path('story8', views.showBook, name="story8"),
    path('data/', views.dataBook, name="data"),
]

story9_app/urls.py
from django.urls import path, include
from . import views

app_name = 'story9_app'
urlpatterns = [
    path('surprise', views.showSurprise, name="surprise"),
    path('login', views.loginPage, name='login'),
    path('register', views.registerPage, name='register'),
    path('logout', views.logoutUser, name='logout'),
]

story4_app/models.py
from django.db import models

# Create your models here.

story4_app/views.py
from django.shortcuts import render

# Create your views here.
def riwayat_view(request):
	return render(request, "pages/riwayat.html")

def portofolio_view(request):
	return render(request, "pages/portofolio.html")

def logs_view(request):
	return render(request, "pages/logs.html")

story4_app/templates/app-shell.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/home.css' %}"/>
    <script src="https://kit.fontawesome.com/7ee84e11dc.js" crossorigin="anonymous"></script>
    {% block meta %}
    {% endblock meta %}
</head>
<body>
    <header>
        <h1 class="header-title">
            Cornelita
        </h1>
        <button type="button" class="btn btn-primary btn-lg" id="hamburger">☰</button>
    </header>

    <nav class="d-flex align-items-center justify-content-center">
        <ul id="drawer" class="nav">
            <li class="nav-item d-flex align-items-center"><a href="/">Beranda</a></li>
            <!-- <li class="nav-item d-flex align-items-center"><a href="/riwayat">Riwayat Hidup</a></li> -->
            <!-- <li class="nav-item d-flex align-items-center"><a href="/portofolio">Portofolio</a></li> -->
            <!-- <li class="nav-item d-flex align-items-center"><a href="/logs">Logs</a></li> -->
            <!-- <li class="nav-item d-flex align-items-center"><a href="/list-matkul">Mata Kuliah</a></li> -->
            <li class="nav-item d-flex align-items-center"><a href="{% url 'story6_app:activity_url' %}">Aktivitas</a></li>
            <li class="nav-item d-flex align-items-center"><a href="{% url 'story7_app:story7' %}">Story 7</a></li>
            <li class="nav-item d-flex align-items-center"><a href="{% url 'story8_app:story8' %}">Story 8</a></li>
            <li class="nav-item d-flex align-items-center"><a href="{% url 'story9_app:surprise' %}">Story 9</a></li>
        </ul>
    </nav>

    <div id="brown-line"></div>
    
    {% block content %}
    {% endblock content %}
    
    <div id="brown-line" class="full"></div>

    <footer>
        <div id="contact" class="row justify-content-center">
            <div class="col-4 d-flex justify-content-center">
                <a href="https://www.instagram.com/cornelita_/">
                    <img class="small-logo" src="{% static 'images/contact/Instagram.png' %}" alt="Instagram's logo">
                </a>
            </div>
            <div class="col-4 d-flex justify-content-center">
                <a href="#">
                    <img class="small-logo" src="{% static 'images/contact/WA.png' %}" alt="Whatsapp's logo">
                </a>
            </div>
            <div class="col-4 d-flex justify-content-center">
                <a href="https://www.linkedin.com/in/cornelita-lugita-santoso">
                    <img class="small-logo" src="{% static 'images/contact/LinkedIn.png' %}" alt="LinkedIn's logo">
                </a>
            </div>
        </div>
    </footer>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="../static/scripts/app.js"></script>
    {% block script %}    
    {% endblock script %}
</body>
</html>